# -*- coding: utf-8 -*-
"""Apredendo o Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ufYIUtAXslwjIKLS_t6KEKFerx4TlryB

# **Importação da  Biblioteca**
"""

import matplotlib.pyplot as plt



"""# **criação do gráfico com plot()**"""

x=[1,2,3,4]
y=[2,3,4,3]
plt.plot(x,y)
plt.show()

"""# Passo 03- **Alteração** do gráfico"""

x=[1,2,3,4]
y=[2,3,4,3]
plt.plot(x,y, label ='dados')
plt.title('Meu primeiro gráfico')
plt.xlabel('Eixo x',color = 'red')
plt.ylabel('Eixo y',color = 'red')
plt.xticks([0,1,2,3,4,5,6])
plt.yticks([0,2,3,4])
plt.legend()
plt.show()

"""# **Propriedades** da linha"""

plt.plot(x,y, linestyle = '--', color = 'm', lw = 2.0, marker='o')
# 'b' como azul, 'g' como verde 'n' como vermelho 'c' como cinza 'm' como magenta 'y' como amarelo 'k' como preto e 'w' como branco
#plt.plot(x,y, linestyle = '-') --> deixa solida
#plt.plot(x,y, linestyle = ':') --> deixa a linha pontilhada
#plt.plot(x,y, linestyle = '-.') --> deixa a linha tracejada e pontilhada
plt.legend('upper left')

plt.show()

"""# Passo 04 - Criação de Gráfico de **disperção scatter()**"""

x=[1,2,3,4]
y=[2,3,4,3]
plt.title('Gráfico de dispersão')
plt.xlabel('Eixo x', color ='red')
plt.ylabel('Eixo y ', color = 'red')
plt.scatter(x,y, label ='dados')
plt.show()

"""# Passo 05- Criação de **Gráfico de Barras**"""

x=[1,2,3,4]
y=[2,3,4,3]
plt.title('Gráfico de Barras')
plt.xlabel('Eixo x', color ='red')
plt.ylabel('Eixo y ', color = 'red')
plt.bar(x,y, label ='dados', color="pink")
plt.show()

"""# **Passo 06- Mudando os tipos de marcadores**"""

x=[1,2,3,4]
y=[2,3,4,3]
plt.scatter(x,y, label ='dados', marker='*')

plt.show()

"""**Alterando os limites dos eixos**"""

x=[1,2,3,4]
y=[2,3,4,3]
plt.plot(x,y)
plt.axis(xmin =-1,xmax= 20,ymin =-5 ,ymax= 15)
plt.show()

x=[1,2,3,4]
y=[2,3,4,3]
plt.plot(x,y)
plt.axis('auto')
plt.show()

"""# Criação de **figuras e suplots()**"""

valoresx=[1,2,3,4]
valoresy=[1,4,2,3]

figura=plt.figure(figsize=(30,4))
figura.suptitle('Analíse Geral')
facecolor ="blue"

figura.add_subplot(131)
plt.plot(valoresx, valoresy, label ='dados')
plt.legend()
plt.title('Gráfico 01')

#segundo gráfico
figura.add_subplot(132)
plt.bar(valoresx, valoresy, label ='dados')
plt.legend()
plt.title('Gráfico 02')

#terceiro gráfico
figura.add_subplot(133)
plt.scatter(valoresx, valoresy, label ='dados')
plt.legend()
plt.title('Gráfico 03')
plt.savefig('grafico.png', dpi = 100)
plt.show(figura)

"""Importação da Base de Dados- Bolsa de valores"""

import pandas as pd
cotacao_df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/datapython2413/04-Exercicio de Matplotlib/indexData.csv')
display(cotacao_df)

"""# Criando um **novo dataframe com três colunas**"""

cotacao_df1 = cotacao_df[['Index','Date','Close']]
display(cotacao_df1)

"""reduzindo para apenas NYA"""

dfremove = cotacao_df1.loc[(cotacao_df1['Index'] != 'NYA')]
cotacao_dffinal = cotacao_df1.drop(dfremove.index)
display(cotacao_dffinal)

cotacao_dffinal = cotacao_dffinal [13900:]
display(cotacao_dffinal)

"""# Criando gráfico com a base de NYA"""

plt.figure(figsize=(20,4))
plt.plot(cotacao_dffinal['Date'], cotacao_dffinal['Close'], label ='NYA', ls = '--', lw = '2')
plt.legend(loc=2, fontsize=18)
plt.axis(xmin = '2021-03-01', xmax = '2021-03-23')
plt.xticks(rotation = 90)
plt.ylabel('Volume do fechamento')
plt.xlabel('Data da Cotação')
plt.title('Cotação do Índice NYA')
plt.show()

