# -*- coding: utf-8 -*-
"""aula01Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HCAhBLrymG4mnAM0rkLCDwEkO3X0opOD

## O que é o **pandas**?

*   É a melhor biblioteca utilizada para dados em Python
*   Utlizar comandos e lógica em programação em Python para realizar análises

# Passo 01- Importar o **Pandas**
"""

import pandas as pd

"""# Passo 02 - Criar a **Dataframe**"""

#dataframe = pd.DataFrame()
venda={'data': ['15/02/2021', '16/02/2021'],
'valor':[500, 300],
'produto': ['Feijão', 'Arroz'],
       'qtde':[50,70]}

vendas_df=pd.DataFrame(venda)

"""# Passo 03 - **Visualizar** o DataFrame"""

display(vendas_df)

"""# Passo 04 -Importar **dados**"""

vendas_df=pd.read_excel('/content/drive/MyDrive/Colab Notebooks/datapython2413/Exercicio Pandas 01/Vendas.xlsx')
display(vendas_df)

"""# Passo 05 - Visualização de **arquivos** **de** **dados**"""

display(vendas_df.head(70))

print(vendas_df.shape)

display(vendas_df.describe())

"""## Passo 06 - **Edição** **do** **DataFrame**"""

produtos= vendas_df[['Produto', 'ID Loja']]
display(produtos)

display(vendas_df.loc[1:5])

display(vendas_df.loc[vendas_df['ID Loja']== 'Shopping Eldorado'])

display(vendas_df.loc[vendas_df['ID Loja']== 'Norte Shopping',['ID Loja','Produto', 'Quantidade']])

vendas_df.to_excel('Test.xlsx', index= False)

print(vendas_df.loc[1, 'Produto'])

"""# Passo 07 - Adicionar **Colunas**"""

vendas_df['Comissão']= vendas_df['Valor Final']*0.05
display(vendas_df)

vendas_df['Imposto'] = 0
display(vendas_df)

vendas_df.loc['Linha', 'Coluna'] = 0
vendas_df.loc[:,'Imposto'] = 0
display(vendas_df)

"""# Passo 08 - **Adicionar Linha**"""

vendas_dez_df=pd.read_excel('/content/drive/MyDrive/Colab Notebooks/datapython2413/Exercicio Pandas 01/Vendas - Dez.xlsx')
display(vendas_dez_df)

vendas_df=pd.concat([vendas_df, vendas_dez_df])
display(vendas_df)

"""# Passo 09 - **Excluir** colunas e Linhas"""

vendas_df = vendas_df.drop('Imposto', axis=1)
display(vendas_df)

vendas_df = vendas_df.drop(0, axis= 0)
display(vendas_df)

"""# Passo 10 - **Tratamento e Análise de Dados**"""

vendas_df =vendas_df.dropna(how='all', axis=1)
display(vendas_df)

"""Para preencher valores vazio com a Média"""

vendas_df['Comissão'] = vendas_df['Comissão'].fillna(vendas_df['Comissão'].mean())
display(vendas_df)

vendas_df = vendas_df.ffill()
display(vendas_df)

"""# Passo 11 - **Calcular Indicadores**"""

transacoes_loja = vendas_df['ID Loja'].value_counts()
display(transacoes_loja)

faturamento_produto = vendas_df[['Produto', 'Valor Final', 'Quantidade']].groupby('Produto').sum()
display(faturamento_produto)

faturamento_produto = vendas_df[['Produto', 'Valor Final', 'Quantidade']].groupby('Produto').mean()
display(faturamento_produto)

"""# Passo 12 - **Mesclar Tabelas**"""

gerentes_df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/datapython2413/Exercicio Pandas 01/Gerentes.xlsx')
display(gerentes_df)

vendas_df = vendas_df.merge(gerentes_df)
display(vendas_df)

